AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

  Environment:
    Type: String
    AllowedValues: ["dev", "qa", "preprod", "prod"]
    Default: "dev"
    Description: "Deployment environment."

  InstanceType:
    Type: String
    Default: "t2.micro"
    AllowedValues: ["t2.micro", "t3.medium", "m5.large"]
    Description: "EC2 instance type."

  EnableEbsEncryption:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"
    Description: "Enable EBS volume encryption."

  KmsKeyId:
    Type: String
    Default: ""
    Description: "KMS Key ID for EBS encryption (if enabled)."

Conditions:
  IsProd: !Equals [!Ref Environment, "prod"]
  UseEncryption: !Equals [!Ref EnableEbsEncryption, "true"]

Rules:
  ProdRestrictInstanceType:
    RuleCondition: !Equals [!Ref Environment, "prod"]
    Assertions:
      - Assert: !Equals [!Ref InstanceType, "m5.large"]
        AssertDescription: "Only 'm5.large' is allowed in production."

  DevRestrictInstanceType:
    RuleCondition: !Equals [!Ref Environment, "dev"]
    Assertions:
      - Assert: !Equals [!Ref InstanceType, "t2.micro"]
        AssertDescription: "Only 't2.micro' is allowed in dev."

  RequireKMSKeyForEncryption:
    RuleCondition: !Equals [!Ref EnableEbsEncryption, "true"]
    Assertions:
      - Assert: !Not [!Equals [!Ref KmsKeyId, ""]]
        AssertDescription: "KMS Key ID must be provided when EBS encryption is enabled."

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref ImageId
      Tags:
        - Key: Environment
          Value: !Ref Environment

  MyEBSVolume:
    Type: AWS::EC2::Volume
    Condition: UseEncryption
    Properties:
      Size: 10
      AvailabilityZone: !Select [0, !GetAZs ""]
      Encrypted: !Ref EnableEbsEncryption
      KmsKeyId: !If [UseEncryption, !Ref KmsKeyId, !Ref "AWS::NoValue"]
      
  MyVolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Condition: UseEncryption
    Properties:
      InstanceId: !Ref MyEC2Instance
      VolumeId: !Ref MyEBSVolume
      Device: /dev/sdh  # Mount point inside the EC2 instance

Outputs:
  InstanceId:
    Description: "EC2 Instance ID"
    Value: !Ref MyEC2Instance
