AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: MyVPC

Outputs:
  VPCId:
    Description: The ID of the created VPC For My Tech Application
    Value: !Ref MyVPC
    Export:
      Name: FinanceApplicationVPC