Parameters:
  StorageName:
    Description: Name of the S3 Bucket
    Type: String
    Default: "js-integrations-dev"

  SecurityGroupDescription:
    Description: Security Group Description (Simple Parameter)
    Type: String

  SecurityGroupPort:
    Description: Description of a Group Port with Min and a Max Value
    Type: Number
    MinValue: 1150
    MaxValue: 65535

  # With SSM
  InstanceType:
    Description: WebServer EC2 instance type
    Type: AWS::SSM::Parameter::Value<String>
    Default: /dev/ec2/instanceType

  # No SSM
  # InstanceType:
  #   Description: WebServer EC2 instance type (has default, Allowed Values)
  #   Type: String
  #   Default: t2.small
  #   AllowedValues:
  #     - t1.micro
  #     - t2.nano
  #     - t2.micro
  #     - t2.small
  #   ConstraintDescription: Must be a valid EC2 Instance Type

  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances. Linked to AWS Parameter
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Must be the name of an existing EC2 KeyPair

  DatabasePwd:
    NoEcho: true
    Description: The database admin account password (won't be echoed)
    Type: String

  CustomVPC:
    Description: VPC to operate in
    Type: AWS::EC2::VPC::Id

  SubnetIds:
    Description: A List of available Subnet Ids
    Type: "List<AWS::EC2::Subnet::Id>"

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      ImageId: ami-0742b4e673072066f
      SubnetId: !Ref DbSubnet1

  DbSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref CustomVPC
      CidrBlock: !Select [0, !Ref DBSubnetIpBlocks]
